### ISSUE TITLE
https://developer-weekly.com/ is out-of-date

### ISSUE THREAD

**Issue by shlomif** [szabgab/developer-weekly.com#5]
The latest issue there is for Sep 2017 and it is June 2018 now. Was DW discontinued?

**Comment by szabgab** [comment]
It is. For now.

**Comment by shlomif** [comment]
On Fri, 22 Jun 2018 22:12:22 -0700
Gabor Szabo <notifications@github.com> wrote:

> Closed #5.
> 

Hi!

I see. Perhaps put a notice to this effect there - see
https://www.joelonsoftware.com/2007/02/19/seven-steps-to-remarkable-customer-service/ .

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Beginners Site for the Vim text editor - http://vim.begin-site.org/

He who reinvents the wheel will likely design a square wheel and spend a year
trying to figure out why it doesn’t work properly.
    — Nadav Har’El, http://www.shlomifish.org/humour.html

Please reply to list if it's a mailing list post - http://shlom.in/reply .
